language: node_js
node_js:
  - "8.11.4"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test-ci

notifications:
  slack: ascespace-de-travail:XEvdeKhyVaf2m9LwpkQKvK9Z